{{- $fullName := include "homelab.fullname" . -}}
{{- range .Values.persistentVolumeClaims }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-%s" $fullName .name }}
  labels:
    app.kubernetes.io/name: {{ include "homelab.name" $ }}
    helm.sh/chart: {{ include "homelab.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  accessModes:
{{ toYaml .accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .size }}
  {{- with .storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  {{- with .volumeMode }}
  volumeMode: {{ . }}
  {{- end }}
{{- end }}
