{{- $fullName := include "homelab.fullname" . -}}
{{- $root := . -}}
{{- $name := include "homelab.name" . }}
{{- $chart:= include "homelab.chart" . }}
{{- $values := .Values }}

{{- if .Values.persistence.enabled }}
{{- range .Values.persistence.volumes }}
  {{- if eq .type "pvc" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-{{ .name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    helm.sh/chart: {{ $chart }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service }}
spec:
  accessModes:
    - {{ .accessMode | default "ReadWriteOnce" | quote }}
  resources:
    requests:
      storage: {{ .size | default "1Gi" }}
  storageClassName: {{ .storageClassName | default "datastore" }}
  volumeMode: Filesystem
{{- end }}
{{- end }}
{{- end }}
