{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "homelab.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "homelab.name" . }}
    helm.sh/chart: {{ include "homelab.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "homelab.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
