global:
  image:
    repository: test 
    tag: test
  securityContext: {}

cronJob:
  name: "test-cronjob"
  schedule: "0 0 * * *"
  args: []
persistence:
  enabled: false

annotations: {}

extraEnvs: []

resources: {}

affinity: {}

tolerations: {}

