global:
  replicaCount: 1
  securityContext: {}
  image:
    repository: test 
    tag: test

service:
  port: 80

ingress:
  enabled: false
  ingressClassName: "nginx-shared-services"
  hosts:
    - host: applications.supli-spirtz.name
      tls:
        secretName: test
      paths:
        - path: /wallos(/|$)(.*)
          pathType: Prefix
          port:
            number: 443

pod:
  labels: {}
  annotations: {}

persistence:
  enabled: false
  
annotations: {}

extraEnvs: []

resources: {}

affinity: {}

tolerations: {}

livenessProbe:
  enabled: false
  httpGet: {}

readinessProbe:
  enabled: false
  httpGet: {}
  
startupProbe:
  enabled: false
  httpGet: {}